"""Remove description from designations

Revision ID: 31b01c3fbb3c
Revises: 92c09f0ee284
Create Date: 2026-07-09 21:49:33.517520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31b01c3fbb3c'
down_revision = '92c09f0ee284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('designations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
