"""added attendance logs and lunch tracking

Revision ID: 39cb99fabbe7
Revises: ce50b9c9c715
Create Date: 2026-06-20 01:17:58.663812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cb99fabbe7'
down_revision = 'ce50b9c9c715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('lunch_minutes')

    # ### end Alembic commands ###
