"""Replace duration fields with seconds

Revision ID: 4d995d810ed1
Revises: e6279af68c68
Create Date: 2026-07-23 16:26:28.318605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d995d810ed1'
down_revision = 'e6279af68c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees_backup')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('working_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lunch_seconds', sa.Integer(), nullable=True))
        batch_op.drop_column('working_hours')
        batch_op.drop_column('lunch_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch_minutes', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('working_hours', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('lunch_seconds')
        batch_op.drop_column('working_seconds')

    op.create_table('employees_backup',
    sa.Column('employee_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('employee_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('department_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('joining_date', sa.DATE(), nullable=True),
    sa.Column('basic_salary', mysql.FLOAT(), nullable=True),
    sa.Column('leave_balance', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_photo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('designation_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
