"""Added GPS fields to branches

Revision ID: 59774910282f
Revises: b74371abfc75
Create Date: 2026-06-12 16:40:15.570927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59774910282f'
down_revision = 'b74371abfc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('allowed_radius', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('allowed_radius')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
