"""Add created_at to leave requests

Revision ID: 624a5feb047c
Revises: 4d995d810ed1
Create Date: 2026-08-07 13:08:08.284927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624a5feb047c'
down_revision = '4d995d810ed1'
branch_labels = None
depends_on = None


def upgrade():

    # Step 1: Add column as nullable
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                nullable=True
            )
        )

    # Step 2: Fill existing rows
    op.execute("""
        UPDATE leave_requests
        SET created_at = NOW()
        WHERE created_at IS NULL
    """)

    # Step 3: Make column NOT NULL
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            nullable=False
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
