"""test migration

Revision ID: 781cf5bacac9
Revises: c549f11cc6b9
Create Date: 2026-06-23 23:20:58.079441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781cf5bacac9'
down_revision = 'c549f11cc6b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('grace_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('shift_id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'shifts', ['shift_id'], ['shift_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('shift_id')

    op.drop_table('shifts')
    # ### end Alembic commands ###
