"""Enhanced employee profile

Revision ID: 83f078c166f5
Revises: 59774910282f
Create Date: 2026-06-12 17:03:15.089697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f078c166f5'
down_revision = '59774910282f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('joining_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('basic_salary', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('leave_balance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('employee_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('employee_photo')
        batch_op.drop_column('leave_balance')
        batch_op.drop_column('basic_salary')
        batch_op.drop_column('joining_date')
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
