"""Add designations table

Revision ID: 92c09f0ee284
Revises: 781cf5bacac9
Create Date: 2026-07-09 21:12:40.248173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c09f0ee284'
down_revision = '781cf5bacac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designations',
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('designation_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('designation_id'),
    sa.UniqueConstraint('designation_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('designations')
    # ### end Alembic commands ###
