"""add lunch start time

Revision ID: c549f11cc6b9
Revises: 5a8d1d8f529c
Create Date: 2026-06-21 11:17:37.701496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c549f11cc6b9'
down_revision = '5a8d1d8f529c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lunch_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lunch_end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('lunch_end_time')
        batch_op.drop_column('lunch_start_time')

    # ### end Alembic commands ###
