"""Replace designation with designation_id

Revision ID: cbfcfb5bc627
Revises: 31b01c3fbb3c
Create Date: 2026-07-11 21:44:01.256281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbfcfb5bc627'
down_revision = '31b01c3fbb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'designations', ['designation_id'], ['designation_id'])
        batch_op.drop_column('designation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('designation_id')

    # ### end Alembic commands ###
