"""Add GPS fields to attendance

Revision ID: e6279af68c68
Revises: cbfcfb5bc627
Create Date: 2026-07-21 11:46:16.983588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6279af68c68'
down_revision = 'cbfcfb5bc627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('login_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('login_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('distance_from_branch', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('distance_from_branch')
        batch_op.drop_column('login_address')
        batch_op.drop_column('login_longitude')
        batch_op.drop_column('login_latitude')

    # ### end Alembic commands ###
