name: Deploy Bindu EMS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            echo "========== Updating Project =========="

            cd ~/bindu-ems

            git fetch --all
            git reset --hard origin/main

            echo "========== Backend =========="

            cd backend

            source venv/bin/activate

            pip install -r requirements.txt

            export FLASK_APP=run.py

            echo "Running database migrations..."
            flask db upgrade

            echo "Restarting Gunicorn..."
            sudo systemctl restart bindu

            echo "========== Frontend =========="

            cd ../bindu-ems-frontend

            /usr/bin/npm install

            chmod +x node_modules/.bin/vite

            /usr/bin/npm run build

            echo "========== Deploying Frontend =========="

            sudo rm -rf /var/www/bindu/*
            sudo cp -r dist/* /var/www/bindu/

            sudo systemctl reload nginx

            echo "========== Deployment Completed =========="